nginx-proxy:
  image: chavisb/nginx-proxy:v1
  cpu_shares: 128
  mem_limit: 524288000
  ports:
   - "80:80"
  links:
   - flaskapp
flaskapp:
  image: chavisb/flaskapp:v1
  cpu_shares: 128
  mem_limit: 524288000
  ports:
   - "5000:5000"
